### ISSUE TITLE
Can not install using `pip install -r requirements.txt` because of open3d

### ISSUE THREAD

**Issue by kwesiRutledge** [ozay-group/kinova-arm#15]
On Max OS X, it is no longer possible to install according to the directions in the main README due to the fact that `open3d`'s support for Macs seems to be lacking. Is there a way to have the installation procedure be different for different operating systems?

**Comment by kwesiRutledge** [comment]
It looks like `pyrealsense2` and `dt_apriltags` also fail when installing on a mac with M1 Max processor. This may be because the processor is not yet supported by many libraries, we may have to ignore this error for now and post a note in the main readme about this.

**Comment by haechan-jeong** [comment]
Open3d can go away if it causes any problem as it was only required for ICP. But it's odd that `pyrealsense2` and `dt_apriltags` are causing problem as they must have ran fine in mac previously. I think defining older versions of `pyrealsense2` and `dt_apriltags` (maybe pyrealsense2=2.51.1 (released in 2022) and dt_apriltag=3.1.7 (released in 2021)?) in the `requirements.txt` may remove the error during installation.

**Comment by kwesiRutledge** [comment]
That is a good point. For now, we can keep the instructions as they are. As long as the installation works on the lab machine, we can leave things be. 

For now, I've just added a small note in the main README about this problem to let users know how to "complete" the install without these libraries. If this issue comes up again, then we can think of a better way to handle this.
