### ISSUE TITLE
Verifying How to Use Virtual Environment on New Lab Laptop

### ISSUE THREAD

**Issue by kwesiRutledge** [ozay-group/kinova-arm#6]
Hey @arw12625 or @Xngzdai !

Is it possible for one of you to check on whether or not the new virtual environment installed on the lab laptop works?

There should be instructions for how to run it here [doc](https://github.com/ozay-group/kinova-arm/blob/11944d083623f5d8ab8a80f0e91c12aa64763f9e/doc/using-the-thinkpad.md). If you test it, then can you reply here with whether it works or not?

**Comment by Xngzdai** [comment]
Specs:
Hardware Model: Lenovo ThinkPad P1 Gen 4i
Memory: 32.0 GiB
Processor: 11th Gen Intel® Core™ i7-11850H @ 2.50GHz × 16
Graphics: llvmpipe (LLVM 13.0.1, 256 bits) / Mesa Intel® UHD Graphics (TGL GT1)
Disk Capacity: 512.1 GB
OS Name: Ubuntu 22.04.1 LTS
OS Type: 64-bit
GNOME Version: 42.4
WIndowing System: Wayland

> The terminal prompt should now be changed, and should show the virtual environment name in parentheses (venv2). (KR: Can someone confirm this?)

Yes. It is confirmed.

**Comment by Xngzdai** [comment]
The file system has been changed severely that the import usually fails.

Task: Run `infinity_demo_hw.py` under venv2.
Issue: `ModuleNotFoundError: No module named 'kinova_station'`
Related code: `sys.path.append('/root/kinova_drake/')`, `from kinova_station import `
Attempt 1: `sys.path.append('~/Documents/manipulation/kinova_drake/')`
Attempt 2: `sys.path.insert(0,'~/Documents/manipulation/kinova_drake/kinova_station/')`
Attempt 3: `from Documents.manipulation.kinova_drake.kinova_station import `

**Comment by kwesiRutledge** [comment]
Great job verifying this! I will close this issue for now!

**Comment by kwesiRutledge** [comment]
In order to fix the new problem that you're seeing, have you tried using the absolute path (i.e. not using special symbols like `~`?

**Comment by Xngzdai** [comment]
Will try and post results below.

**Comment by kwesiRutledge** [comment]
Strangely, I remember running `drake/velocity_control1/hw_velocity_command_test.py` using the laptop (Maybe I'm wrong here? It looks like the wrong path is in the current commit, so I'm probably wrong.). There might be a solution in that file if I added something that wasn't in the commit.

**Comment by Xngzdai** [comment]
Hi! Sorry for the late reply. I'm back from the midterm week!

Would you mind sharing your procedures of running `drake/velocity_control1/hw_velocity_command_test.py`? I tried some path introduction and discovered that `kinova_drake` cannot be imported while launching the virtual environment under the current directory structure. 1) `kinova_drake` is on the same level as `kinova-arm`. It is not a sub directory. 2) The program imports modules inside the virtual packages. `pip install` is required to install outside user-defined packages. 3) `kinova_drake` is not encapsulated as an available package in `.tar.gz` so it cannot be `pip install`-ed.

I might not bother with the file system for now. I will temporarily work inside docker as before until I am granted time or approval to re-structure the file system. Still, there may be an easy way to solve this and I didn't think of. Feel free to pop up any ideas.

Source: 
https://stackoverflow.com/a/61350103
https://stackoverflow.com/a/63819291

**Comment by kwesiRutledge** [comment]
Very thorough response! Thanks!

> Would you mind sharing your procedures of running drake/velocity_control1/hw_velocity_command_test.py? I tried some path introduction and discovered that kinova_drake cannot be imported while launching the virtual environment under the current directory structure.

Unfortunately, it's been a while since I've used the laptop and the only thing that I remembered was the instructions I shared with you. If you would like, you can try to run the code _outside_ of the virtual environment. It is possible that I gave up on using the virtual environment and installed everything on the python that is built into the machine.

> I might not bother with the file system for now. I will temporarily work inside docker as before until I am granted time or approval to re-structure the file system. Still, there may be an easy way to solve this and I didn't think of. Feel free to pop up any ideas.

I understand that you prefer to work with Docker and encourage you to keep using it!

I am concerned with the problems you(?) experienced with getting Docker to connect to the camera and arm. If issues prevented you from connecting properly, then they might impact others. Fixing the issues by having a dedicated computer that can connect to the arm and camera seems to be the best solution for future students + long-term projects. If we don't have something in place, then when you graduate we may have little hope of reproducing your results without bringing you back to campus. :'(

**Comment by Xngzdai** [comment]
> Unfortunately, it's been a while since I've used the laptop and the only thing that I remembered was the instructions I shared with you. If you would like, you can try to run the code outside of the virtual environment. It is possible that I gave up on using the virtual environment and installed everything on the python that is built into the machine.

It is worth trying to run codes locally. Though, I have a few considerations based on my experiences with the code.

- An encapsulated environment is a good practice to manage dependency and prevent interference with other projects that simultaneously run on the same laptop (though Necmiye intended to specialize the usage per laptop).
- In my opinion, venv is no different than docker on the previous point. But venv seems to be more flexible than docker as it is usually painful to renew docker image. Also, no bother with virtual-real machine connection is another merit.
- I believe there exists a method like a dependency checklist in venv that can specify and configure the environment. But it may need some work.
- In terms of this "checklist", docker is a cure-all method. Running shell scripts is sufficient and the codes will be ready to go.

We should think of these tradeoffs and decide which one we prefer. I have no problem in setting up the environment for future usage. But I have a capstone project going on this semester so I shall work on setups and cleanups next semester when I have finished my main duty.

I'm sorry if this keeps you on call for a period of time.
